spring:
  redis:
    database: 0
    host: 101.43.137.147
    port: 6379
    password: root # 如果未单独配置默认为空即可
    timeout: 1000
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
